form disp horarias y excepciones mejorado
santicasalis/ConnectInk pull request #256
Opened 2023-12-12 20:02 UTC by ludmiviale

se pueden editar las disponibilidades horarias y eliminar las excepciones :D

2023-12-12 20:47 UTC, alejoguzmann approved these changes

2023-12-12 20:54 UTC, santicasalis approved these changes

2023-12-12 20:56 UTC, santicasalis requested changes
tiene conflictos no toque por las dudas

2023-12-12 22:02 UTC, 1991facundo commented
Habria que ver que onda con el css que se encuentra abajo

2023-12-13 00:46 UTC, PGochman approved these changes

2023-12-13 00:47 UTC, Constanzamw approved these changes

2023-12-13 00:47 UTC, Constanzamw approved these changes

2023-12-13 00:47 UTC, PGochman approved these changes

2023-12-13 00:48 UTC, merged